# Generated by Django 2.0 on 2018-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
