# Generated by Django 2.0 on 2018-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180901_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='icon',
            field=models.ImageField(blank=True, upload_to='providers/'),
        ),
    ]
