# Generated by Django 2.0 on 2019-02-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_provider_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='full_name',
        ),
        migrations.AddField(
            model_name='bio',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bio',
            name='last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
