# Generated by Django 2.0 on 2019-02-12 19:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20190211_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bio',
            new_name='UserProfile',
        ),
    ]
