# Generated by Django 2.0 on 2019-02-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190212_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestatus',
            name='status',
        ),
        migrations.AddField(
            model_name='coursestatus',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
